from __future__ import annotations # fixes the circular dependency
from pydantic import BaseModel, EmailStr, Field
from datetime import date
from typing import Optional
# Pydantic is a data validatio library
# Inheriting base model
# Validation
# .json() (sending back to react in json format)

""" Schema for Course """
class CourseBase(BaseModel):
    course_name: str
    duration: int
    skill_level: str
    course_fees: int

class CourseCreate(CourseBase):
    program_id: int
    institute_id: int

class Course(CourseBase):
    course_id: int

    institute_id: int
    program_id: int
    textbook: Optional[Textbook] = None
    videos: list[Video] = []
    notes: list[Notes] = []
    topics: list[Topic] = []
    instructors: list[Instructor] = []

    class Config:
        from_attributes = True

""" Schema for Student """
class StudentBase(BaseModel):
    name: str
    email_id : EmailStr
    specialization: str
    country: Optional[str] = None
    skill_level: Optional[str] = "Beginner"

class StudentCreate(StudentBase):
    """What we expect from React when a student signs up"""
    dob: date
    # ... indicates the mandatory
    password: str = Field(..., min_length=8)
    contact_number: str
    specialization: str

class Student(StudentBase):
    """What we send back to React (includes the ID generated by DB)"""
    student_id: int

    courses : list[Course] = []

    class Config:
        # Allows pydantic to read the attributes from the object
        from_attributes = True

""" Schema for Instructor """
class InstructorBase(BaseModel):
    name: str
    email_id: EmailStr
    department: str

class InstructorCreate(InstructorBase):
    dob: date
    password: str = Field(...,min_length=8)

class Instructor(InstructorBase):

    instructor_id: int

    courses: list[Course] = []

    class Config:
        from_attributes = True


""" Schema for University """
class UniversityBase(BaseModel):
    name: str
    city: str
    country: str

class UniversityCreate(UniversityBase):
    pass

class University(UniversityBase):
    institute_id: int

    courses: list[Course] = []
    class Config:
        from_attributes = True

""" Schema for Program """
class ProgramBase(BaseModel):
    program_name: str

class ProgramCreate(ProgramBase):
    pass

class Program(ProgramBase):
    program_id: int
    courses: list[Course] = []
    
    class Config:
        from_attributes = True

""" Schema for Topic """
class TopicBase(BaseModel):
    topic_name: str

class TopicCreate(TopicBase):
    pass

class Topic(TopicBase):
    topic_id: int
    courses: list[Course] = []
    class Config:
        from_attributes = True
        
""" Schema for Textbook """
class TextbookBase(BaseModel):
    title: str
    author: str
    publisher: str
    edition: Optional[str] = None

class TextbookCreate(TextbookBase):
    course_id: int # One-to-One link

class Textbook(TextbookBase):
    textbook_id: int
    class Config:
        from_attributes = True

""" Schema for Video """
class VideoBase(BaseModel):
    title: str
    url_link: str
    duration: int

class VideoCreate(VideoBase):
    course_id: int

class Video(VideoBase):
    video_id: int
    class Config:
        from_attributes = True

""" Schema for Notes """
class NotesBase(BaseModel):
    title: str
    url_link: str  
    document_type: str

class NotesCreate(NotesBase):
    course_id: int

class Notes(NotesBase):
    notes_id: int
    class Config:
        from_attributes = True

""" Schema for System Admin """
class SystemAdminBase(BaseModel):
    name: str
    email_id: EmailStr

class SystemAdminCreate(SystemAdminBase):
    password : str = Field(...,min_length=8)

class SystemAdmin(SystemAdminBase):
    admin_id: int

    class Config:
        from_attributes = True

""" Schema for Data Analyst """
class DataAnalystBase(BaseModel):
    name: str
    email_id: EmailStr

class DataAnalystCreate(DataAnalystBase):
    password : str = Field(...,min_length=8)

class DataAnalyst(DataAnalystBase):
    analyst_id: int

    class Config:
        from_attributes = True
