from __future__ import annotations # fixes the circular dependency
from pydantic import BaseModel, EmailStr, Field
from datetime import date
from datetime import datetime
from typing import List, Optional
# Pydantic is a data validatio library
# Inheriting base model
# Validation
# .json() (sending back to react in json format)

""" Schema for Course """
class CourseBase(BaseModel):
    course_name: str
    duration: int
    skill_level: str
    course_fees: int

class CourseCreate(CourseBase):
    program_id: int
    institute_id: int

class Course(CourseBase):
    course_id: int

    institute_id: int
    program_id: int
    textbook: Optional[Textbook] = None
    videos: list[Video] = []
    notes: list[Notes] = []
    assignment: list[Assignment] = []

    class Config:
        from_attributes = True

""" Schema for Student """
class StudentBase(BaseModel):
    name: str
    email_id : EmailStr
    specialization: Optional[str] = None
    country: Optional[str] = None
    skill_level: Optional[str] = "Beginner"
    
# This allows React to send ONLY the fields that changed
class StudentUpdate(BaseModel):
    name: Optional[str] = None
    email_id: Optional[EmailStr] = None
    dob: Optional[date] = None
    country: Optional[str] = None
    specialization: Optional[str] = None
    skill_level: Optional[str] = None

class StudentCreate(StudentBase):
    """What we expect from React when a student signs up"""
    dob: Optional[date] = None
    # ... indicates the mandatory
    password: str = Field(..., min_length=8)
    contact_number: str
    specialization: str

class Student(StudentBase):
    """What we send back to React (includes the ID generated by DB)"""
    student_id: int
    dob: Optional[date] = None

    class Config:
        # Allows pydantic to read the attributes from the object
        from_attributes = True

""" Schema for Instructor """
class InstructorBase(BaseModel):
    name: str
    email_id: EmailStr
    department: str

class InstructorCreate(InstructorBase):
    dob: date
    password: str = Field(...,min_length=8)

class Instructor(InstructorBase):

    instructor_id: int
    name: str
    email_id: EmailStr
    department: Optional[str] = None
    dob: Optional[date] = None

    class Config:
        from_attributes = True

class InstructorUpdate(BaseModel):
    name: Optional[str] = None
    email_id: Optional[EmailStr] = None
    department: Optional[str] = None
    dob: Optional[date] = None

    class Config:
        from_attributes = True


""" Schema for University """
class UniversityBase(BaseModel):
    name: str
    city: str
    country: str

class UniversityCreate(UniversityBase):
    pass

class University(UniversityBase):
    institute_id: int

    class Config:
        from_attributes = True

""" Schema for Program """
class ProgramBase(BaseModel):
    program_type: str

class ProgramCreate(ProgramBase):
    pass

class Program(ProgramBase):
    program_id: int
    
    class Config:
        from_attributes = True

""" Schema for Topic """
class TopicBase(BaseModel):
    topic_name: str

class TopicCreate(TopicBase):
    pass

class Topic(TopicBase):
    topic_id: int
    class Config:
        from_attributes = True
        
""" Schema for Textbook """
class TextbookBase(BaseModel):
    title: str
    author: str
    publisher: str
    edition: Optional[str] = None

class TextbookCreate(TextbookBase):
    pass

class Textbook(TextbookBase):
    textbook_id: int
    class Config:
        from_attributes = True

""" Schema for Video """
class VideoBase(BaseModel):
    title: str
    url_link: str
    duration: int

class VideoCreate(VideoBase):
    pass

class Video(VideoBase):
    video_id: int
    class Config:
        from_attributes = True

""" Schema for Notes """
class NotesBase(BaseModel):
    title: str
    url_link: str  
    document_type: str

class NotesCreate(NotesBase):
    pass

class Notes(NotesBase):
    notes_id: int
    class Config:
        from_attributes = True

""" Schema for System Admin """
class SystemAdminBase(BaseModel):
    name: str
    email_id: EmailStr

class SystemAdminCreate(SystemAdminBase):
    password : str = Field(...,min_length=8)

class SystemAdmin(SystemAdminBase):
    admin_id: int
    dob: Optional[date] = None

    class Config:
        from_attributes = True

class SystemAdminUpdate(BaseModel):
    name: Optional[str] = None
    email_id: Optional[EmailStr] = None
    dob: Optional[date] = None


""" Schema for Data Analyst """
class DataAnalystBase(BaseModel):
    name: str
    email_id: EmailStr

class DataAnalystCreate(DataAnalystBase):
    password : str = Field(...,min_length=8)

class DataAnalyst(DataAnalystBase):
    analyst_id: int
    dob: Optional[date] = None

    class Config:
        from_attributes = True

class DataAnalystUpdate(BaseModel):
    name: Optional[str] = None
    email_id: Optional[EmailStr] = None
    dob: Optional[date] = None


""" Schema for Assignment """
class AssignmentBase(BaseModel):
    title: str
    description: str
    assignment_url_link: str
    submission_url_link: str
    due_date: date
    marks: int

class AssignmentCreate(AssignmentBase):
    pass

class Assignment(AssignmentBase):
    assignment_id: int
    class Config:
        from_attributes = True


""" Schema for User """
class UserLogin(BaseModel):
    email: EmailStr
    password: str
    
class UserBase(BaseModel):
    email: EmailStr
    full_name: str
    role: str

class UserCreate(UserBase):
    password: str
    enrollment_key: Optional[str] = None # For Instructor/Analyst verification

class User(UserBase):
    id: int

    class Config:
        from_attributes = True # Allows Pydantic to read SQLAlchemy models

# schemas.py
class GradeUpdate(BaseModel):
    marks: int = Field(..., ge=0, le=100) # Validates marks are between 0-100
    grade: str
    pass_fail: str


class SubmissionBase(BaseModel):
    submission_url: str # Or HttpUrl for stricter validation
    assignment_id: int

class SubmissionCreate(SubmissionBase):
    """Used when a student submits their work"""
    # student_id is usually taken from the Auth token, not the body
    pass

class SubmissionUpdate(BaseModel):
    """Used by the Instructor to grade the submission"""
    obtained_marks: int
    status: str # e.g., "Graded"

class StudentSubmission(SubmissionBase):
    """The full representation of the submission"""
    submission_id: int
    student_id: int
    submitted_at: datetime
    obtained_marks: Optional[int] = None
    status: Optional[str] = "Pending"

    class Config:
        from_attributes = True


class CourseCreateWithInstructors(BaseModel):
    course_name: str
    duration: int
    skill_level: str
    course_fees: int
    program_type: str
    institute_name: str
    instructor_emails: List[EmailStr]


""" Admin Course Control Schemas """
class CourseControlPerson(BaseModel):
    name: str
    id: int
    email: EmailStr

class CourseControlResponse(BaseModel):
    course_name: str
    course_id: int
    instructors: List[CourseControlPerson] = []
    students: List[CourseControlPerson] = []

# -------------- APPENDED STATISTICS & ANALYTICS SCHEMAS --------------
# Add this to the end of backend/schemas.py

class StatsOverview(BaseModel):
    courses: int
    students: int
    instructors: int
    universities: int

class CourseBrief(BaseModel):
    course_id: int
    course_name: str
    instructor_name: Optional[str] = None
    institute_name: Optional[str] = None
    registrations: int

class InstructorBrief(BaseModel):
    instructor_id: int
    name: str
    avg_registrations: Optional[float] = 0.0

class UniversityBrief(BaseModel):
    institute_id: int
    name: str
    courses_count: int

class CourseDetail(BaseModel):
    course_id: int
    course_name: str
    instructor_name: Optional[str]
    institute_name: Optional[str]
    registrations: int

class InstructorCoursesList(BaseModel):
    instructor_id: int
    name: str
    courses: List[CourseBrief] = []

class UniversityCoursesList(BaseModel):
    institute_id: int
    name: str
    courses: List[CourseBrief] = []

# Analytics schemas
class GrossRevenueResponse(BaseModel):
    gross_revenue: int

class AvgCourseRevenueResponse(BaseModel):
    avg_revenue: float

class CourseRevenueDetail(BaseModel):
    course_id: int
    course_name: str
    registrations: int
    revenue: int

class InstructorRevenueBreakdown(BaseModel):
    instructor_id: int
    name: str
    total_revenue: int
    courses: List[CourseRevenueDetail] = []

class InstructorRevenueList(BaseModel):
    instructors: List[InstructorRevenueBreakdown] = []

class CourseRevenueList(BaseModel):
    courses: List[CourseRevenueDetail] = []

class CountryRegistration(BaseModel):
    country: str
    students: int

class CountryRegistrationList(BaseModel):
    countries: List[CountryRegistration] = []

